# Generated by Django 5.0.4 on 2024-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=246)),
                ('email', models.CharField(max_length=246)),
                ('password', models.CharField(max_length=246)),
                ('img', models.ImageField(blank=True, default='1.jpg', upload_to='')),
                ('type', models.CharField(max_length=246)),
            ],
        ),
    ]
