# Generated by Django 5.0.4 on 2024-08-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='age',
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='number',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
    ]
