# Generated by Django 5.0.4 on 2024-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_doctor_name_doctor_age_doctor_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_name', models.CharField(max_length=246)),
                ('bio', models.CharField(max_length=246)),
            ],
        ),
    ]
