# Generated by Django 5.0.4 on 2024-08-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dt_name',
            new_name='name',
        ),
    ]
