# Generated by Django 5.0.4 on 2024-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_dt_name_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=246)),
                ('email', models.CharField(max_length=246)),
                ('password', models.CharField(max_length=246)),
                ('number', models.CharField(max_length=246)),
                ('age', models.CharField(max_length=246)),
                ('gender', models.CharField(max_length=246)),
                ('type', models.CharField(max_length=246)),
            ],
        ),
    ]
