# Generated by Django 5.0.4 on 2024-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_billingadmin_hadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingadmin',
            old_name='bio',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hadmin',
            old_name='bio',
            new_name='email',
        ),
        migrations.AddField(
            model_name='billingadmin',
            name='number',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingadmin',
            name='password',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingadmin',
            name='type',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadmin',
            name='number',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadmin',
            name='password',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadmin',
            name='type',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
    ]
