# Generated by Django 5.0.4 on 2024-09-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medicine1',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine2',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine3',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
    ]
