# Generated by Django 5.0.4 on 2024-09-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_patient_medicine1_patient_medicine2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=246)),
                ('medicine', models.CharField(max_length=246)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicine1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicine2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicine3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='type',
        ),
    ]
