# Generated by Django 5.0.4 on 2024-09-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_prescription_remove_patient_medicine1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prescription',
            new_name='pprescription',
        ),
    ]
