# Generated by Django 5.0.4 on 2024-09-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_pprescription_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='type',
            new_name='date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='time',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=246)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
        ),
    ]
