# Generated by Django 5.0.4 on 2024-09-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_type_doctor_date_doctor_time_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
