# Generated by Django 5.0.4 on 2024-09-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='img',
            field=models.ImageField(blank=True, default='1.jpg', upload_to=''),
        ),
    ]
