# Generated by Django 5.0.4 on 2024-09-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingadmin',
            name='type',
        ),
        migrations.RemoveField(
            model_name='hadmin',
            name='type',
        ),
    ]
