# Generated by Django 5.0.4 on 2024-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_billingadmin_type_remove_hadmin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reg_date',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
    ]
