# Generated by Django 5.0.4 on 2024-09-20 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_patient_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
