# Generated by Django 5.0.4 on 2024-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
