# Generated by Django 5.0.4 on 2024-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
