# Generated by Django 5.0.4 on 2024-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_booking_is_confirmed_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=246),
        ),
    ]
