# Generated by Django 5.0.4 on 2024-10-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_doctor_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='departments',
        ),
    ]
