# Generated by Django 5.0.4 on 2024-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_department_doctor_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprescription',
            name='quantity',
            field=models.CharField(default=1, max_length=246),
            preserve_default=False,
        ),
    ]
